export const INPUT_CHANGE = "INPUT_CHANGE";
export const CLEAN_INPUT = "CLEAN_INPUT";
export const WEATHER_SEARCH = "WEATHER_SEARCH";
export const API_CALL_FULFILLED = "API_CALL_FULFILLED";
export const API_CALL_REJECTED = "API_CALL_REJECTED";
export const API_CALL_PENDING = "API_CALL_PENDING";
export const SEARCHEDCITY_LIST_UPDATE = "SEARCHEDCITY_LIST_UPDATE";
export const SLIDER_INIT = "SLIDER_INIT";
