export const INPUT_CHANGE = "INPUT_CHANGE";
export const CLEAN_INPUT = "CLEAN_INPUT";
export const WEATHER_SEARCH = "WEATHER_SEARCH";
export const API_CALL_FULFILLED = "API_CALL_FULFILLED";
export const API_CALL_REJECTED = "API_CALL_REJECTED";
